"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var datastructures_1 = require("./datastructures");
var test = new datastructures_1.maxHeapBased();
test.push('a', 1);
test.push('b', 2);
test.push('c', 3);
test.push('d', 4);
test.push('e', 5);
test.push('f', 6);
test.push('g', 7);
test.push('h', 8);
test.push('i', 9);
test.push('j', 10);
test.push('k', 11);
test.push('l', 12);
test.push('m', 13);
test.push('n', 14);
test.push('o', 15);
test.push('p', 16);
test.push('q', 17);
test.push('r', 18);
test.push('s', 19);
test.push('t', 20);
var result = test.top();
console.log('nothing works');
